#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Jan 26 12:22:18 PKT 2022
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim pwm_tb_behav -key {Behavioral:sim_1:Functional:pwm_tb} -tclbatch pwm_tb.tcl -view /home/rehan/MERL/FPGA_EMU/PWM_MOTOR_SPEED_CTL/pwm_tb_behav.wcfg -log simulate.log
